apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: production
spec:
  clusterIP: 10.128.73.53
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30121
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
