apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    volume: my-volume
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: 192.168.0.1
    path: "/exports"
