apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-cliam
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      volume: my-volume
