apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-load-balancer
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
    nodePort: 30000
  selector:
    app: api
  sessionAffinity: None
  type: LoadBalancer
