apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: data
  namespace: default
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: api
  clusterIP: None

