#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: database
#  labels:
#    volume: my-volume-claim
#  namespace: default
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
#  selector:
#    matchLabels:
#      volume: my-volume


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-example
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain
